#!/bin/bash

wget -O- https://repo.radeon.com/rocm/rocm.gpg.key | gpg --dearmor | sudo tee /usr/share/keyrings/rocm-keyring.gpg > /dev/null

echo 'deb [arch=amd64 signed-by=/usr/share/keyrings/rocm-keyring.gpg] https://repo.radeon.com/amdgpu/latest/ubuntu jammy proprietary' | sudo tee /etc/apt/sources.list.d/amdgpu-proprietary.list
echo 'deb [arch=amd64 signed-by=/usr/share/keyrings/rocm-keyring.gpg] https://repo.radeon.com/amdgpu/latest/ubuntu jammy main' | sudo tee /etc/apt/sources.list.d/amdgpu.list
echo 'deb [arch=amd64 signed-by=/usr/share/keyrings/rocm-keyring.gpg] https://repo.radeon.com/rocm/apt/debian/ jammy main' | sudo tee /etc/apt/sources.list.d/rocm.list
echo -e 'Package: *\nPin: release o=repo.radeon.com\nPin-Priority: 600' | sudo tee /etc/apt/preferences.d/repo-radeon-pin-600

sudo apt update

sudo apt upgrade

sudo apt install amdgpu-install 


sudo amdgpu-install --usecase=rocm --no-dkms

wget https://raw.githubusercontent.com/ROCmSoftwarePlatform/MIOpen/develop/utils/install_precompiled_kernels.sh && chmod +x install_precompiled_kernels.sh && ./install_precompiled_kernels.sh

rocminfo
